# Generated by Django 4.1 on 2023-11-23 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('target_text', models.TextField()),
                ('source_language', models.CharField(max_length=10)),
                ('target_language', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='translate',
            name='query',
        ),
        migrations.AddField(
            model_name='translate',
            name='query_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='translate.query'),
        ),
    ]
