# Generated by Django 4.1 on 2023-11-28 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_query_remove_translate_query_translate_query_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translate',
            name='query_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.query'),
        ),
    ]
